#配置文件修改方法: 配置 : 参数    :符号前后要有一个空格 示例: path : E:\Work\
#文件夹路径样式 eg: E:\Work\
#文件路径样式 eg: E:\Work\三家运营商代垫电费出账工具V35V1-20200901.xlsm
#附件需要存在path参数文件夹下的"缴费所需资料"内
#一个标准的缴费文件夹结构
#   \*path*\内有软件用导入模板,报账点信息
path :  #缴费资料的文件夹的路径需要在路径后面加一个\号 eg:E:\Work\
letterPath :  #分摊比例函文件 eg:E:\Work\0759\QT-004-关于商请湛江移动确认共享基站2020年7月电费分摊比例的函.zip
toolName : 

#1号用户
userName1 : 
user1 : 
password1 : 

#2号用户
userName2 : 
user2 : 
password2 : 